# -*- coding: utf-8 -*-
"""data_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DvsjQtDcVyfKM_IR6CqNjb7Iv63WY4bw
"""



import pandas as pd

# Step 1: Load raw sales data
def load_data(file_path):
    print("📥 Loading data...")
    df = pd.read_csv(file_path)
    print(f"✅ Loaded {df.shape[0]} rows.")
    return df

# Step 2: Clean and transform data
def clean_data(df):
    print("🧹 Cleaning data...")
    # Drop rows with missing key columns
    df = df.dropna(subset=["Order Date", "Region", "Product", "Sales"])

    # Convert dates
    df["Order Date"] = pd.to_datetime(df["Order Date"])

    # Ensure numeric columns are clean
    df["Sales"] = pd.to_numeric(df["Sales"], errors='coerce')
    df["Profit"] = pd.to_numeric(df["Profit"], errors='coerce')

    # Fill missing numeric values with 0
    df.fillna({"Profit": 0}, inplace=True)

    print("✅ Data cleaned.")
    return df

# Step 3: Save cleaned data
def save_data(df, output_file):
    df.to_csv(output_file, index=False)
    print(f"💾 Cleaned data saved to {output_file}")

# Main workflow
if __name__ == "__main__":
    input_csv = "raw_sales_data.csv"     # replace with actual file path
    output_csv = "cleaned_sales_data.csv"

    df_raw = load_data(input_csv)
    df_clean = clean_data(df_raw)
    save_data(df_clean, output_csv)